/*
** /boot/home/work/bework/ot-dockbert-current/opentracker/deskbar/othericons.h
**
** Automatically generated by BResourceParser on
** Monday, April 15, 2002 at 18:04:06.
**
*/

enum {
	R_CloseButton = 50,
	R_ShowAllButton = 51,
	R_HideAllButton = 52,
	R_SmallSign2 = 53,
	R_SeparatorIcon = 55,
	R_HomeIcon = 58,
	R_HomeIconSmall = 59,
	R_ShowDesktopIcon = 60,
	R_ShowDesktopIconSmall = 61,
	R_DisksIcon = 62,
	R_DisksIconSmall = 63,
	R_BringAllHereButton = 64,
	R_WorkspacesIcon = 65,
	R_SmallSign = 66,
	R_FlashSign = 67
};
